const USERS = [
    
    {
        id: 0,
        name: "Tchanga",
        lastName: "Ulrich",
        tel:'698672248',
        email: 'tchangaulrich@gmail.com',
        sexe: 'homme',
        status:'teacher',
        mdp:'1234',
    },
    {
        id: 1,
        name: "Noumechi",
        lastName: "Lionnel",
        tel:'694891111',
        email: 'lionnelnoumechi@gmail.com',
        sexe: 'homme',
        status:'teacher',
        mdp:'1234',
    },
    {
        id: 2,
        name: "Dantio",
        lastName: "patrick",
        tel:'698672248',
        email: 'dantiopatrick@gmail.com',
        sexe: 'homme',
        status:'student',
        mdp:'1234',
    },
    {
        id: 3,
        name: "Kaptue",
        lastName: "Audrey",
        tel:'694891111',
        email: 'kaptueaudrey@gmail.com',
        sexe: 'femme',
        status:'student',
        mdp:'1234',
    },
    {
        id: 4,
        name: "Tajeumi",
        lastName: "warene",
        tel:'698672248',
        email: 'tajeumiwarene@gmail.com',
        sexe: 'homme',
        status:'student',
        mdp:'1234',
    },
    {
        id: 5,
        name: "toto",
        lastName: "titus",
        tel:'698672248',
        email: 'tototitus@gmail.com',
        sexe: 'homme',
        status:'student',
        mdp:'1234',
    },

]

export default USERS